package errs

import (
	"errors"
)

var (
	ErrPasswordTooShort      = errors.New("password must be at least 8 characters long")
	ErrPasswordNoUppercase   = errors.New("password must contain at least one uppercase letter")
	ErrPasswordNoLowercase   = errors.New("password must contain at least one lowercase letter")
	ErrPasswordNoNumber      = errors.New("password must contain at least one number")
	ErrPasswordNoSpecialChar = errors.New("password must contain at least one special character")

	ErrEmailAlreadyInUse = errors.New("email already in use")

	ErrAuthTokenUserIDRequired     = errors.New("user ID is required")
	ErrAuthTokenTokenRequired      = errors.New("token is required")
	ErrAuthTokenExpirationRequired = errors.New("expiration time is required")
	ErrAuthTokenIDRequired         = errors.New("ID is required")

	ErrUserIDRequired                      = errors.New("user ID is required and must be greater than zero")
	ErrPasswordHashRequired                = errors.New("password hash is required")
	ErrPasswordHashTooShort                = errors.New("password hash appears to be too short (minimum 32 characters)")
	ErrPasswordHashTooLong                 = errors.New("password hash exceeds maximum length of 255 characters")
	ErrConfirmationTokenRequired           = errors.New("confirmation token is required")
	ErrConfirmationTokenTooShort           = errors.New("confirmation token must be at least 16 characters long")
	ErrConfirmationTokenTooLong            = errors.New("confirmation token exceeds maximum length of 255 characters")
	ErrConfirmationExpirationRequired      = errors.New("confirmation expiration time is required")
	ErrConfirmationExpirationMustBeFuture  = errors.New("confirmation expiration time must be in the future")
	ErrResetPasswordTokenRequired          = errors.New("reset password token is required")
	ErrResetPasswordTokenTooShort          = errors.New("reset password token must be at least 16 characters long")
	ErrResetPasswordTokenTooLong           = errors.New("reset password token exceeds maximum length of 255 characters")
	ErrResetPasswordExpirationRequired     = errors.New("reset password expiration time is required")
	ErrResetPasswordExpirationMustBeFuture = errors.New("reset password expiration time must be in the future")
	ErrCreatedAtRequired                   = errors.New("created at timestamp is required")
	ErrUpdatedAtRequired                   = errors.New("updated at timestamp is required")
	ErrUpdatedAtBeforeCreatedAt            = errors.New("updated at timestamp cannot be before created at timestamp")

	ErrEmailRequired                        = errors.New("email is required")
	ErrEmailTooLong                         = errors.New("email exceeds maximum length of 320 characters")
	ErrEmailInvalidFormat                   = errors.New("invalid email format: missing @ symbol or invalid position")
	ErrEmailMultipleAtSymbols               = errors.New("invalid email format: multiple @ symbols found")
	ErrEmailLocalPartEmpty                  = errors.New("email local part cannot be empty")
	ErrEmailLocalPartTooLong                = errors.New("email local part exceeds maximum length of 64 characters")
	ErrEmailLocalPartConsecutiveDots        = errors.New("email local part cannot contain consecutive dots")
	ErrEmailLocalPartStartEndDot            = errors.New("email local part cannot start or end with a dot")
	ErrEmailLocalPartInvalidCharacters      = errors.New("email local part contains invalid characters")
	ErrEmailDomainEmpty                     = errors.New("email domain cannot be empty")
	ErrEmailDomainTooLong                   = errors.New("email domain exceeds maximum length of 255 characters")
	ErrEmailDomainStartEndDot               = errors.New("email domain cannot start or end with a dot")
	ErrEmailDomainStartEndHyphen            = errors.New("email domain cannot start or end with a hyphen")
	ErrEmailDomainMustContainDot            = errors.New("email domain must contain at least one dot")
	ErrEmailDomainConsecutiveDots           = errors.New("email domain cannot contain consecutive dots")
	ErrEmailDomainMinimumLabels             = errors.New("email domain must have at least two labels")
	ErrEmailDomainLabelEmpty                = errors.New("email domain label cannot be empty")
	ErrEmailDomainLabelTooLong              = errors.New("email domain label exceeds maximum length of 63 characters")
	ErrEmailTopLevelDomainTooShort          = errors.New("email top-level domain must be at least 2 characters")
	ErrEmailTopLevelDomainInvalidCharacters = errors.New("email top-level domain must contain only letters")
	ErrEmailDomainLabelStartEndHyphen       = errors.New("email domain label cannot start or end with hyphen")
	ErrEmailDomainLabelInvalidCharacters    = errors.New("email domain label contains invalid characters")

	ErrNameRequired                 = errors.New("name is required")
	ErrNameTooShort                 = errors.New("name must be at least 2 characters long")
	ErrNameTooLong                  = errors.New("name cannot exceed 255 characters")
	ErrNameMustStartWithLetter      = errors.New("name must start with a letter")
	ErrNameMustEndWithLetterOrDigit = errors.New("name must end with a letter or digit")
	ErrNameConsecutiveSpaces        = errors.New("name cannot contain consecutive spaces")
	ErrNameInvalidCharacters        = errors.New(
		"name contains invalid characters (only letters, digits, spaces, hyphens, apostrophes, and periods are allowed)",
	)
	ErrNameCannotStartOrEndWithSpaces      = errors.New("name cannot start or end with spaces")
	ErrNameCannotStartWithPunctuation      = errors.New("name cannot start with punctuation")
	ErrNameCannotEndWithPunctuation        = errors.New("name cannot end with punctuation")
	ErrNameExcessiveConsecutivePunctuation = errors.New("name cannot contain more than 3 consecutive punctuation marks")

	ErrConfirmationTokenIsNil = errors.New("confirmation token is nil")
)
