package model

type VideoMetadataModel struct {
	id                       uint64
	autoGeneratedDescription string
	ageRating                uint8
	ageRateExplanation       string
	ageRatingCategories      []string
	version                  string
}

func (vm VideoMetadataModel) ID() uint64 {
	return vm.id
}

func (vm VideoMetadataModel) AutoGeneratedDescription() string {
	return vm.autoGeneratedDescription
}

func (vm VideoMetadataModel) AgeRating() uint8 {
	return vm.ageRating
}

func (vm VideoMetadataModel) AgeRateExplanation() string {
	return vm.ageRateExplanation
}

func (vm VideoMetadataModel) AgeRatingCategories() []string {
	return vm.ageRatingCategories
}

func (vm VideoMetadataModel) Version() string {
	return vm.version
}
