package model

type VideoMetadataModel struct {
	id                       uint64
	autoGeneratedDescription string
	ageRating                uint8
	ageRateExplanation       string
	ageRatingCategories      []string
	version                  string
}
