name: CI

on:
  push:
    # Runs on every push to any branch (change to [main] if you want only main)
    branches: [ "**" ]
  pull_request:

jobs:
  build-and-test:
    name: Lint, Vulnerability Check, Test, Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Download dependencies
        run: go mod download

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Lint (golangci-lint)
        run: make lint

      - name: Vulnerability Check
        run: make vuln-check

      - name: Test and generate coverage report
        run: make cover

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
